### ISSUE TITLE
Make .urlignore ignore based on whole URL instead of just hostname

### ISSUE THREAD

**Issue by cyberw** [zalando-incubator/Transformer#81]
The urlignore/denylist functionality doesnt actually ignore based on url, it only checks hostname/netloc. This is a huge limitation (and doesnt match the documentation). 

I have a PR that changes this, but since there are actually tests that verify this behaviour I think it is intentional, so I wanted to check first.

**Comment by thilp** [comment]
Hi @cyberw, thanks for reaching out! I don’t recall why only the hostname is checked, and I can’t think of a good reason for it today, so imho applying the denylist to the whole URL would be a valuable feature. Just like in #80, we should probably enable it via some sort of explicit configuration (e.g. CLI flag or environment variable) to make sure existing usages don’t break surprisingly.

Since it’s about the way the denylist is interpreted, another possibility could be to add a "magic comment" at the top of the denylist file, or use a specific suffix (e.g. `.urlignore.full` or `.urlignore.v2`).

We could also combine this feature with your regex idea from #80.

What do you think?

**Comment by ePaul** [comment]
Without knowing much about this tool, I suppose this was meant to restrict the generated test to the system which we actually want to test, and ignore others which are used from the website which is recorded. For this, a domain-based filtering would normally be enough.

Of course that's not a reason to prevent filtering by other parts of the URL.
